#!/bin/sh

readonly repo_root="$(git rev-parse --show-toplevel)"

# warn and block commit for formatting changes
echo "Running pre-commit validation"
pipenv run yapf --diff --recursive --exclude '*migrations*' --parallel "$repo_root" >/dev/null
exit_status="$?"
if [ "$exit_status" -ne 0 ]; then
    pipenv run yapf --in-place --recursive --exclude '*migrations*' "$repo_root" --parallel
    >&2 echo "Review formatting changes"
fi

exit "$exit_status"
