version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    links:
      - redis
