version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: daphne --bind 0.0.0.0 --port 8000 dancingtogether.asgi:application
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    links:
      - redis
