version: "3"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=dancingtogether.settings.development
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - REDIS_URL=redis://redis@redis:6379
    env_file:
      - .envrc
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
