# Generated by Django 2.0.2 on 2018-02-12 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('admins', models.ManyToManyField(related_name='admin_room_set', to=settings.AUTH_USER_MODEL)),
                ('djs', models.ManyToManyField(related_name='dj_room_set', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='room_set', to=settings.AUTH_USER_MODEL)),
                ('pending_users', models.ManyToManyField(related_name='pending_room_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
