# Generated by Django 2.0.2 on 2018-02-13 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listener',
            old_name='room',
            new_name='station',
        ),
        migrations.AlterField(
            model_name='station',
            name='members',
            field=models.ManyToManyField(related_name='stations', through='radio.Listener', to=settings.AUTH_USER_MODEL),
        ),
    ]
