# Generated by Django 2.0.2 on 2018-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20180213_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='context_uri',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='station',
            name='current_track_uri',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='station',
            name='paused',
            field=models.NullBooleanField(default=None),
        ),
    ]
