# Generated by Django 2.0.2 on 2018-02-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20180217_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='position_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
