# Generated by Django 2.0.2 on 2018-02-24 20:04
# Edited on 2018-05-14 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_spotifycredentials_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifycredentials',
            name='access_token_expiration_time',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2018, 2, 24, 20, 4, 33, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
