# Generated by Django 2.0.3 on 2018-03-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_spotifycredentials_access_token_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_uri', models.CharField(default='', max_length=256)),
                ('current_track_uri', models.CharField(default='', max_length=256)),
                ('paused', models.NullBooleanField(default=None)),
                ('position_ms', models.PositiveIntegerField(default=0)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spotifycredentials',
            options={'verbose_name_plural': 'spotify credentials'},
        ),
        migrations.RemoveField(
            model_name='station',
            name='context_uri',
        ),
        migrations.RemoveField(
            model_name='station',
            name='current_track_uri',
        ),
        migrations.RemoveField(
            model_name='station',
            name='paused',
        ),
        migrations.RemoveField(
            model_name='station',
            name='position_ms',
        ),
        migrations.AddField(
            model_name='playbackstate',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='radio.Station'),
        ),
    ]
