# Generated by Django 2.0.3 on 2018-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20180321_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbackstate',
            name='context_uri',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='playbackstate',
            name='current_track_uri',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='playbackstate',
            name='paused',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='playbackstate',
            name='position_ms',
            field=models.PositiveIntegerField(),
        ),
    ]
