# Generated by Django 2.0.3 on 2018-03-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20180321_0417'),
        ('radio', '0008_auto_20180321_0809'),
    ]

    operations = [
    ]
