# Generated by Django 2.0.5 on 2018-05-25 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_merge_20180331_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbackstate',
            old_name='position_ms',
            new_name='raw_position_ms',
        ),
        migrations.AddField(
            model_name='playbackstate',
            name='sample_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
