# Generated by Django 2.0.6 on 2018-06-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_auto_20180525_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinglistener',
            name='room',
        ),
        migrations.RemoveField(
            model_name='pendinglistener',
            name='user',
        ),
        migrations.RemoveField(
            model_name='station',
            name='pending_members',
        ),
        migrations.DeleteModel(
            name='PendingListener',
        ),
    ]
