# Generated by Django 2.0.7 on 2018-07-11 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0011_auto_20180629_0634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listener',
            unique_together={('user', 'station')},
        ),
    ]
