#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

# install frontend dependencies

(cd "$REPO_ROOT/frontend" && npm install)

# install backend dependencies

# Install postgresql-dev for psycopg2-binary Python dependency
sudo apt-get install postgresql-dev

python3 -m pip install --upgrade pip pipenv
pipenv install --dev --system --ignore-pipfile --deploy
