#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

# install frontend dependencies

(cd "$REPO_ROOT/frontend" && npm install)

# install backend dependencies

python -m pip install --upgrade pip pipenv
pipenv install --dev --system --ignore-pipfile --deploy
