#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

mkdir -p junit

# run frontend lint tests

(cd "$REPO_ROOT/frontend" && npm run --silent lint -- --format junit >../junit/test-frontend-lint.xml)

# run backend lint tests

yapf --recursive . --exclude '*/migrations/*' --parallel --diff
mypy --ignore-missing-imports --junit-xml junit/test-backend-mypy.xml $(find . -name \*.py ! -path '*/migrations/*')
pylint --rcfile pyproject.toml --output-format=pylint_junit.JUnitReporter accounts dancingtogether main radio >junit/test-backend-pylint.xml
