#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

mkdir -p junit

# run frontend lint tests

(cd "$REPO_ROOT/frontend" && npx tslint --project tsconfig.prod.json --format junit --out ../junit/test-frontend-lint.xml)

# run backend lint tests

python3 -m black --check .
python3 -m mypy --ignore-missing-imports --junit-xml junit/test-backend-lint.xml $(find . -name \*.py ! -path '*/migrations/*')
find . -name '*.py' ! -path '*/migrations/*' -print0 | xargs pylint --load-plugins pylint_django
